import { makeAugmentedSchema } from "neo4j-graphql-js"
import { typeDefs } from "./Domains/MyDomain/typeDefs"
import { resolvers } from "./Domains/MyDomain/resolvers"
import { schemaDirectives } from "./Domains/MyDomain/Directives"

/*
 * Create an executable GraphQL schema object from GraphQL type definitions
 * including autogenerated queries and mutations.
 * Optionally a config object can be included to specify which types to include
 * in generated queries and/or mutations. Read more in the docs:
 * https://grandstack.io/docs/neo4j-graphql-js-api.html#makeaugmentedschemaoptions-graphqlschema
 */

export const schema = makeAugmentedSchema({
  typeDefs,
  resolvers,
  schemaDirectives,
  /** turning auto-creation off */
  config: {
    query: false, 
    mutation: false
  }
})
